/**
 * ImmobIA symbol: two houses whose roof outline is a rising growth line ending in a point.
 * Icon cut (heavier line) for UI sizes; the door is a hole, so the tile behind shows through.
 * Source artwork: immobia-marca/final (generated by final.py).
 */
export function BrandMark({ className }: { className?: string }) {
  return (
    <svg aria-hidden="true" className={className} viewBox="0 0 64 64">
      <g fill="currentColor" fillRule="evenodd" transform="translate(0.5 -2.4)">
        <path d="M10.2 53 L10.2 44.7 L19 35.9 L23.21 40.11 L23.21 53 Z" />
        <path d="M26.79 53 L26.79 40.11 L40 26.9 L54.4 41.3 L54.4 53 Z M37.4 43.4 H42.6 V53 H37.4 Z" />
      </g>
      <g fill="var(--brand-line, #f5c518)" transform="translate(0.5 -2.4)">
        <path
          d="M9 39 L19 29 L25 35 L40 20"
          fill="none"
          stroke="var(--brand-line, #f5c518)"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="3.6"
        />
        <circle cx="40" cy="20" r="3.38" />
      </g>
    </svg>
  );
}
